novas_questoes = [{'titulo': 'Quando foi lançado o primeiro videogame?',
                    'nivel': 'facil',
                    'opcoes': {'A': '1990', 'B': '1985', 'C': '1972', 'D': '2013'},
                    'correta': 'C'},
                    {'titulo': 'Qual desses filmes teve a maior bilheteria da história?',
                    'nivel': 'facil',
                    'opcoes': {'A': 'Avatar', 'B': 'Vingadores: Ultimato', 'C': 'Titanic', 'D': 'Gente Grande'},
                    'correta': 'A'},
                    {'titulo': 'Qual é o jogador de futebol mais caro do mundo?',
                    'nivel': 'medio',
                    'opcoes': {'A': 'Neymar Jr.', 'B': 'Haaland', 'C': 'Mbappé', 'D': 'Cristiano Ronaldo'},
                    'correta': 'C'},
                    {'titulo': 'Qual foi o ano em que o Brasil ganhou a sua 5a Copa do Mundo?',
                    'nivel': 'medio',
                    'opcoes': {'A': '2007', 'B': '1998', 'C': '2002', 'D': '2006'},
                    'correta': 'C'},
                    {'titulo': 'Qual desses é o artista com mais ouvintes mensais no Spotify?',
                    'nivel': 'dificil',
                    'opcoes': {'A': 'The Weeknd', 'B': 'BTS', 'C': 'Taylor Swift', 'D': 'Drake'},
                    'correta': 'C'}
]